config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2020 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, only: [:new, :create]
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
  member do
    get "agile_data", :to => "agile_boards#agile_data"
  end
end

resources :agile_queries

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'

app/controllers/agile_charts_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2020 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileChartsController < ApplicationController
  unloadable

  menu_item :agile

  before_action :find_optional_project, :only => [:show, :render_chart]
  before_action :find_optional_version, :only => [:render_chart, :select_version_chart]

  helper :issues
  helper :journals
  helper :projects
  include ProjectsHelper
  helper :custom_fields
  include CustomFieldsHelper
  helper :issue_relations
  include IssueRelationsHelper
  helper :watchers
  include WatchersHelper
  helper :attachments
  include AttachmentsHelper
  helper :queries
  include QueriesHelper
  helper :repositories
  include RepositoriesHelper
  helper :sort
  include SortHelper
  include IssuesHelper
  helper :timelog
  include RedmineAgile::AgileHelper

  def show
    retrieve_charts_query
    @query.date_to ||= Date.today
    @issues = @query.issues
    respond_to do |format|
      format.html
    end
  end

  def render_chart
    if @version
      @issues = @version.fixed_issues
      options = { date_from: @version.start_date,
                  date_to: [@version.due_date,
                            @issues.maximum(:due_date),
                            @issues.maximum(:updated_on)].compact.max,
                  due_date: @version.due_date || @issues.maximum(:due_date) || @issues.maximum(:updated_on),
                  chart_unit: params[:chart_unit] }
      @chart = params[:chart]
    else
      retrieve_charts_query
      @issues = Issue.visible
      @issues = @issues.where(@query.statement)
      options = { date_from: @query.date_from,
                  date_to: @query.date_to,
                  interval_size: @query.interval_size,
                  chart_unit: @query.chart_unit }
    end
    render_data(options)
  end

  def select_version_chart
  end

  private

  def render_data(options = {})
    agile_chart = RedmineAgile::Charts::AGILE_CHARTS[@chart]
    data = agile_chart[:class].data(@issues, options) if agile_chart

    if data
      data[:chart] = @chart
      data[:chart_unit] = options[:chart_unit]
      return render json: data
    end

    raise ActiveRecord::RecordNotFound
  end

  def find_optional_version
    @version = Version.find(params[:version_id]) if params[:version_id]
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def retrieve_charts_query
    if params[:query_id].present?
      @query = AgileChartsQuery.find(params[:query_id])
      raise ::Unauthorized unless @query.visible?
      @query.project = @project
    elsif params[:set_filter] || session[:agile_charts_query].nil? || session[:agile_charts_query][:project_id] != (@project ? @project.id : nil)
      # Give it a name, required to be valid
      @query = AgileChartsQuery.new(:name => '_')
      @query.project = @project
      @query.build_from_params(params)
      session[:agile_charts_query] = { project_id: @query.project_id,
                                       filters: @query.filters,
                                       group_by: @query.group_by,
                                       column_names: @query.column_names,
                                       date_from: @query.date_from,
                                       date_to: @query.date_to,
                                       interval_size: @query.interval_size,
                                       chart: @query.chart,
                                       chart_unit: @query.chart_unit }
    else
      # retrieve from session
      @query = AgileChartsQuery.new(name: '_',
                                    filters: session[:agile_charts_query][:filters] || session[:agile_query][:filters],
                                    group_by: session[:agile_charts_query][:group_by],
                                    column_names: session[:agile_charts_query][:column_names],
                                    date_from: session[:agile_charts_query][:date_from],
                                    date_to: session[:agile_charts_query][:date_to],
                                    interval_size: session[:agile_charts_query][:interval_size],
                                    chart: session[:agile_charts_query][:chart],
                                    chart_unit: session[:agile_charts_query][:chart_unit])
      @query.project = @project
    end
    @chart = params[:chart] || @query.chart
  end
end

app/helpers/agile_charts_helper.rb
# encoding: utf-8
#
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2020 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

module AgileChartsHelper
  def render_agile_charts_breadcrumb
    links = []
    links << link_to(l(:label_project_all), project_id: nil, issue_id: nil)
    links << link_to(h(@project), project_id: @project, issue_id: nil) if @project
    if @version
      links << @version.visible? ? link_to(@version.name, version_path(@version)) : @version.name
    end
    breadcrumb links
  end
end

app/views/agile_charts/_agile_charts.html.erb
<% if User.current.allowed_to?(:view_agile_charts, @project, :global => true) %>

  <ul class=agile-chart-queries>
  </ul>
<% end %>

app/views/agile_charts/_chart.html.erb
<% if issues_scope.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% elsif %w(work_burndown cumulative_flow hours_velocity).include?(chart) && issues_scope.count > RedmineAgile.time_reports_items_limit %>
  <p class="nodata"><%= l(:label_agile_too_many_items, :max => RedmineAgile.time_reports_items_limit) %></p>
<% else %>
  <div class="agile-chart-container">
    <canvas id="agile-chart"></canvas>
    <div style="clear: both;"></div>
  </div>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function(){
    Chart.plugins.register({
      beforeDraw: function(chartInstance, easing) {
        if (chartInstance.config.options.tooltips.onlyShowForDatasetIndex) {
          var tooltipsToDisplay = chartInstance.config.options.tooltips.onlyShowForDatasetIndex;
          var active = chartInstance.tooltip._active || [];
          if (active.length > 0) {
            if (tooltipsToDisplay.indexOf(active[0]._datasetIndex) === -1) {
              chartInstance.tooltip._model.opacity = 0;
            }
          }
        }
      }
    });

    if (document.getElementById("agile-chart")) {
      $.getJSON(<%= raw url_for(controller: 'agile_charts', action: 'render_chart', project_id: @project,
                                chart: chart, version_id: @version, query_id: @query.try(:id), chart_unit: chart_unit).to_json %>, function(data){

        Chart.defaults.global.defaultFontColor = 'black';
        Chart.defaults.global.defaultFontFamily = '"Arial", sans-serif';
        Chart.defaults.global.defaultFontStyle = 'normal';

        var chartData = {
          labels: data['labels'],
          datasets: data['datasets'],
          stacked: data['stacked']
        };

      new Chart(document.getElementById("agile-chart").getContext("2d"), {
        type: data['type'] || 'bar',
        data: chartData,
        options: {
          tooltips: {
            onlyShowForDatasetIndex: data['show_tooltips'],
            callbacks: chartTooltipCallbacks(data['type'])
          },
          maintainAspectRatio: false,
          legend: {
            position: 'right',
            labels: {
              filter: function(legendItem, chartData) {
                if (legendItem.text) { return true }
              }
            }
          },
          title: {
            display: true,
            fontSize: 16,
            fontStyle: 'normal',
            text: data['title']
          },
          elements: {
            line: {
                tension: 0, // disables bezier curves
            }
          },
          scales: {
            yAxes: [{
              stacked: data['stacked'],
              scaleLabel: {
                display: true,
                fontColor: 'rgba(255, 0, 0 ,1)',
                fontSize: 14,
                labelString: data['y_title']
              }
            }],
            xAxes: [{
              ticks: {
                autoSkip: true,
                maxRotation: 0,
                userCallback: function(value, index, values) {
                  if (data['type'] == 'scatter') {
                    return data['labels'][value]
                  } else {
                    return value
                  }
                }
              }
            }]
            },
          }
        });
      });
    }
  });
<% end %>

app/views/agile_charts/_versions_show.html.erb
<% if @issues.any? && User.current.allowed_to?(:view_agile_charts, @project) %>
  <fieldset>
    <legend>
      <%= l(:label_agile_chart) %>
      <%= select_tag('chart', options_charts_for_select(params[:chart] || RedmineAgile.default_chart),
                     id: 'chart_by_select',
                     onchange: "toggleChartUnit($(this).val(), 'chart-unit-row'); updateVersionAgileChart('#{agile_charts_select_version_chart_path(version_id: @version)}');") %>

      <span id="chart-unit-row">
        <label for='chart_unit'><%= l(:label_agile_chart_units) %></label>
        <%= select_tag 'chart_unit', options_chart_units_for_select,
                       onchange: "updateVersionAgileChart('#{agile_charts_select_version_chart_path(version_id: @version)}');" %>
      </span>
    </legend>
    <div id='agile_chart'>
      <%= render_agile_chart(RedmineAgile::Charts.valid_chart_name_by(params[:chart] || RedmineAgile.default_chart), @version.fixed_issues) %>
    </div>
  </fieldset>
<% end %>

<% content_for :header_tags do %>
  <%= chartjs_assets %>
  <%= javascript_include_tag 'redmine_agile', plugin: 'redmine_agile' %>
<% end %>

<%= javascript_tag do %>
  var chartsWithUnits = <%= raw RedmineAgile::Charts::CHARTS_WITH_UNITS.to_json %>
  $(document).ready(function() {
    toggleChartUnit($('#chart_by_select').val(), 'chart-unit-row');
  });
<% end %>

app/views/agile_charts/select_version_chart.js.erb
$('#agile_chart').html('<%= escape_javascript(render_agile_chart(params[:chart], @version.fixed_issues)) %>');

if ("replaceState" in window.history) {
  window.history.replaceState(null, document.title, "?chart=<%= params[:chart] %>");
}

app/views/agile_charts/show.html.erb
<%= render_agile_charts_breadcrumb %>

<h2><%= @query.new_record? ? l(:label_agile_chart_plural) : h(@query.name) %></h2>
<% html_title(@query.new_record? ? l(:label_agile_chart_plural) : @query.name) %>

<%= form_tag({ :controller => 'agile_charts', :action => 'show', :project_id => @project },
            :method => :get, :id => 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content">
      <fieldset id="filters" class="collapsible">
        <legend class="icon icon-expended" onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
        <div>
          <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
        </div>
      </fieldset>
      <fieldset class="collapsible">
        <legend class="icon icon-expended" onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
        <div>
          <table>
            <tr>
              <td><label for='chart'><%= l(:label_agile_chart) %></label></td>
              <td><%= select_tag 'chart', options_charts_for_select(@chart), onchange: "toggleChartUnit($(this).val(), 'chart-unit-row');" %></td>
              <td id="chart-unit-row">
                <label for='chart_unit'><%= l(:label_agile_chart_units) %></label>
                <%= select_tag 'chart_unit', options_chart_units_for_select(@query.chart_unit) %>
              </td>
            </tr>
            <tr id="interval-size">
              <td><%= l(:label_agile_interval_size) %></td>
              <td>
                <%= select_tag 'interval_size', options_for_select(RedmineAgile::AgileChart::TIME_INTERVALS.map { |i| [l(:"label_agile_#{i}"), i] }, @query.interval_size) %>
              </td>
            </tr>
          </table>
        </div>
      </fieldset>
    </div>
    <p class="buttons">
      <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
      <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
    </p>
  </div>
<% end %>

<%= error_messages_for 'query' %>

<%= render_agile_chart(@chart, @issues) if @query.valid? %>

<% content_for :header_tags do %>
  <%= chartjs_assets %>
  <%= javascript_include_tag 'redmine_agile', plugin: 'redmine_agile' %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'agile_boards/issues_links' %>
  <%= render :partial => 'agile_charts/agile_charts' %>
<% end %>

<%= javascript_tag do %>
  var chartsWithUnits = <%= raw RedmineAgile::Charts::CHARTS_WITH_UNITS.to_json %>
  $(document).ready(function() {
    toggleChartUnit($('#chart').val(), 'chart-unit-row');
    /* Hide chart_period checkbox so that it couldn't be unchecked */
    hideChartPeriodCheckbox();
  });
<% end %>